
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('resources').del()
    .then(function () {
      // Inserts seed entries
      return knex('resources').insert([
        {resource_type_id:1 ,name: 'bamboo', gold_value: 0.01},
        {resource_type_id:1 ,name: 'cotton', gold_value: 0.01},
        {resource_type_id:1 ,name: 'hemp', gold_value: 0.01},
        {resource_type_id:1 ,name: 'jute', gold_value: 0.01},
        {resource_type_id:1 ,name: 'seaweed', gold_value: 0.01},
        {resource_type_id:1 ,name: 'silk', gold_value: 0.01},
        {resource_type_id:1 ,name: 'straw', gold_value: 0.01},
        {resource_type_id:1 ,name: 'fibers', gold_value: 0.01},
        {resource_type_id:2 ,name: 'bark', gold_value: 0.01},
        {resource_type_id:2 ,name: 'fronds', gold_value: 0.01},
        {resource_type_id:2 ,name: 'reeds', gold_value: 0.01},
        {resource_type_id:2 ,name: 'roots', gold_value: 0.01},
        {resource_type_id:2 ,name: 'rushes', gold_value: 0.01},
        {resource_type_id:2 ,name: 'twigs', gold_value: 0.07},
        {resource_type_id:2 ,name: 'thatch', gold_value: 0.01},
        {resource_type_id:3 ,name: 'agedwood', gold_value: 0.03},
        {resource_type_id:3 ,name: 'darkwood', gold_value: 0.05},
        {resource_type_id:3 ,name: 'lightwood', gold_value: 0.03},
        {resource_type_id:3,name: 'softwood', gold_value: 0.03},
        {resource_type_id:3 ,name: 'strongwood', gold_value: 0.03},
        {resource_type_id:3 ,name: 'wetwood', gold_value: 0.03},
        {resource_type_id:3 ,name: 'ironwood', gold_value: 0.05},
        {resource_type_id:3 ,name: 'wood', gold_value: 0.03},
        {resource_type_id:4 ,name: 'honey', gold_value: 0.03},
        {resource_type_id:4 ,name: 'gum', gold_value: 0.03},
        {resource_type_id:4 ,name: 'nectar', gold_value: 0.03},
        {resource_type_id:4 ,name: 'sugars', gold_value: 0.03},
        {resource_type_id:4 ,name: 'sugarcane', gold_value: 0.03},
        {resource_type_id:4 ,name: 'syrup', gold_value: 0.03},
        {resource_type_id:4 ,name: 'resin', gold_value: 0.03},
        {resource_type_id:4 ,name: 'sugar', gold_value: 0.03},
        {resource_type_id:5 ,name: 'anthracite', gold_value: 0.01},
        {resource_type_id:5 ,name: 'graphite', gold_value: 0.01},
        {resource_type_id:5 ,name: 'lignite', gold_value: 0.01},
        {resource_type_id:5 ,name: 'nitre', gold_value: 0.01},
        {resource_type_id:5 ,name: 'peat', gold_value: 0.01},
        {resource_type_id:5 ,name: 'sulfer', gold_value: 0.01},
        {resource_type_id:5 ,name: 'coal', gold_value: 0.01},
        {resource_type_id:6 ,name: 'agate', gold_value: 2.0},
        {resource_type_id:6 ,name: 'basalt', gold_value: 0.01},
        {resource_type_id:6 ,name: 'chalcedony', gold_value: 0.01},
        {resource_type_id:6 ,name: 'chert', gold_value: 0.01},
        {resource_type_id:6 ,name: 'obsidian', gold_value: 0.2},
        {resource_type_id:6 ,name: 'radiolarite', gold_value: 0.01},
        {resource_type_id:6 ,name: 'flint', gold_value: 0.01},
        {resource_type_id:7 ,name: 'coquina', gold_value: 0.03},
        {resource_type_id:7 ,name: 'granite', gold_value: 0.03},
        {resource_type_id:7 ,name: 'limestone', gold_value: 0.03},
        {resource_type_id:7 ,name: 'marble', gold_value: 0.03},
        {resource_type_id:7 ,name: 'sandstone', gold_value: 0.03},
        {resource_type_id:7 ,name: 'slate', gold_value: 0.03},
        {resource_type_id:7 ,name: 'stone', gold_value: 0.03},
        {resource_type_id:8 ,name: 'cobalt', gold_value: 0.07},
        {resource_type_id:8 ,name: 'copper', gold_value: 0.07},
        {resource_type_id:8 ,name: 'iridium', gold_value: 0.1},
        {resource_type_id:8 ,name: 'iron', gold_value: 0.07},
        {resource_type_id:8 ,name: 'silver', gold_value: 0.07},
        {resource_type_id:8 ,name: 'tin', gold_value: 0.07},
        {resource_type_id:8 ,name: 'metal', gold_value: 0.07},
        {resource_type_id:9 ,name: 'cobalt ingot', gold_value: 0.16},
        {resource_type_id:9 ,name: 'copper ingot', gold_value: 0.16},
        {resource_type_id:9 ,name: 'iridium ingot', gold_value: 0.16},
        {resource_type_id:9 ,name: 'iron ingot', gold_value: 0.16},
        {resource_type_id:9 ,name: 'silver ingot', gold_value: 0.16},
        {resource_type_id:9 ,name: 'tin ingot', gold_value: 0.16},
        {resource_type_id:9 ,name: 'alloy', gold_value: 0.16},
        {resource_type_id:10 ,name: 'amethyst', gold_value: 0.05},
        {resource_type_id:10 ,name: 'calcite', gold_value: 0.05},
        {resource_type_id:10 ,name: 'herkimer', gold_value: 0.05},
        {resource_type_id:10 ,name: 'pearl', gold_value: 0.05},
        {resource_type_id:10 ,name: 'quartz', gold_value: 0.05},
        {resource_type_id:10 ,name: 'tellurite', gold_value: 0.05},
        {resource_type_id:10 ,name: 'crystal', gold_value: 0.05},
        {resource_type_id:11 ,name: 'diamond', gold_value: 0.05},
        {resource_type_id:11 ,name: 'emerald', gold_value: 0.05},
        {resource_type_id:11 ,name: 'garnet', gold_value: 0.05},
        {resource_type_id:11 ,name: 'opal', gold_value: 0.05},
        {resource_type_id:11 ,name: 'ruby', gold_value: 0.05},
        {resource_type_id:11 ,name: 'sunstone', gold_value: 0.05},
        {resource_type_id:11 ,name: 'gem', gold_value: 0.05},
        {resource_type_id:12 ,name: 'flake salt', gold_value: 0.02},
        {resource_type_id:12 ,name: 'iodine', gold_value: 0.02},
        {resource_type_id:12 ,name: 'kala namak', gold_value: 0.02},
        {resource_type_id:12 ,name: 'pink salt', gold_value: 0.02},
        {resource_type_id:12 ,name: 'rock salt', gold_value: 0.02},
        {resource_type_id:12 ,name: 'sea salt', gold_value: 0.02},
        {resource_type_id:12 ,name: 'salt', gold_value: 0.02},
        {resource_type_id:13 ,name: 'fleece', gold_value: 0.02},
        {resource_type_id:13 ,name: 'fur', gold_value: 0.02},
        {resource_type_id:13 ,name: 'hair', gold_value: 0.02},
        {resource_type_id:13 ,name: 'leather', gold_value: 0.02},
        {resource_type_id:13 ,name: 'pelt', gold_value: 0.02},
        {resource_type_id:13 ,name: 'skin', gold_value: 0.02},
        {resource_type_id:13 ,name: 'hide', gold_value: 0.02},
        {resource_type_id:14 ,name: 'carapace', gold_value: 0.1},
        {resource_type_id:14 ,name: 'karatanoid', gold_value: 0.02},
        {resource_type_id:14 ,name: 'bone', gold_value: 0.02},
        {resource_type_id:14 ,name: 'residue', gold_value: 0.2},
        {resource_type_id:14 ,name: 'scale', gold_value: 0.02},
        {resource_type_id:14 ,name: 'shell', gold_value: 0.02},
        {resource_type_id:14 ,name: 'generic karatanoid', gold_value: 0.02},
        {resource_type_id:15 ,name: 'brain coral', gold_value: 0.01},
        {resource_type_id:15 ,name: 'fire coral', gold_value: 0.01},
        {resource_type_id:16 ,name: 'organic paste', gold_value: 0.04},
        {resource_type_id:16 ,name: 'organic paste coral', gold_value: 0.04},
        {resource_type_id:17 ,name: 'blubber', gold_value: 0.07},
        {resource_type_id:17 ,name: 'crude oil', gold_value: 0.05},
        {resource_type_id:17 ,name: 'fish oil', gold_value: 0.05},
        {resource_type_id:17 ,name: 'mineral oil', gold_value: 0.05},
        {resource_type_id:17 ,name: 'naptha', gold_value: 0.05},
        {resource_type_id:17 ,name: 'shale oil', gold_value: 0.05},
        {resource_type_id:17 ,name: 'oil', gold_value: 0.05},
        {resource_type_id:18 ,name: 'mythos', gold_value: 2.0},
        {resource_type_id:19 ,name: 'gunpowder', gold_value: 0.03},
        {resource_type_id:19 ,name: 'blasting powder', gold_value: 0.17},
        {resource_type_id:19 ,name: 'fire gel', gold_value: 0.07},
        {resource_type_id:19 ,name: 'perserving salt', gold_value: 0.03},       
      ]);
    });
};
						