
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('resources').del()
    .then(function () {
      // Inserts seed entries
      return knex('resources').insert([
        {name: 'bamboo', type:'fibers'},
        {name: 'cotton', type:'fibers'},
        {name: 'hemp', type:'fibers'},
        {name: 'jute', type:'fibers'},
        {name: 'seaweed', type:'fibers'},
        {name: 'silk', type:'fibers'},
        {name: 'straw', type:'fibers'},
        {name: 'fibers', type:'fibers'},
        {name: 'bark', type:'thatch'},
        {name: 'fronds', type:'thatch'},
        {name: 'reeds', type:'thatch'},
        {name: 'roots', type:'thatch'},
        {name: 'rushes', type:'thatch'},
        {name: 'twigs', type:'thatch'},
        {name: 'thatch', type:'thatch'},
        {name: 'agedwood', type:'wood'},
        {name: 'darkwood', type:'wood'},
        {name: 'lightwood', type:'wood'},
        {name: 'softwood', type:'wood'},
        {name: 'strongwood', type:'wood'},
        {name: 'wetwood', type:'wood'},
        {name: 'ironwood', type:'wood'},
        {name: 'wood', type:'wood'},
        {name: 'honey', type:'sugar'},
        {name: 'gum', type:'sugar'},
        {name: 'nectar', type:'sugar'},
        {name: 'sugars', type:'sugar'},
        {name: 'sugarcane', type:'sugar'},
        {name: 'syrup', type:'sugar'},
        {name: 'resin', type:'sugar'},
        {name: 'sugars', type:'sugar'},
        {name: 'anthracite', type:'coal'},
        {name: 'graphite', type:'coal'},
        {name: 'lignite', type:'coal'},
        {name: 'nitre', type:'coal'},
        {name: 'peat', type:'coal'},
        {name: 'sulfer', type:'coal'},
        {name: 'coal', type:'coal'},
        {name: 'agate', type:'flint'},
        {name: 'basalt', type:'flint'},
        {name: 'chalcedony', type:'flint'},
        {name: 'chert', type:'flint'},
        {name: 'obsidian', type:'flint'},
        {name: 'radiolarite', type:'flint'},
        {name: 'flint', type:'flint'},
        {name: 'coquina', type:'stone'},
        {name: 'granite', type:'stone'},
        {name: 'limestone', type:'stone'},
        {name: 'marble', type:'stone'},
        {name: 'sandstone', type:'stone'},
        {name: 'slate', type:'stone'},
        {name: 'stone', type:'stone'},
        {name: 'cobalt', type:'metal'},
        {name: 'copper', type:'metal'},
        {name: 'iridium', type:'metal'},
        {name: 'iron', type:'metal'},
        {name: 'silver', type:'metal'},
        {name: 'tin', type:'metal'},
        {name: 'metal', type:'metal'},
        {name: 'cobalt ingot', type:'alloy'},
        {name: 'copper ingot', type:'alloy'},
        {name: 'iridium ingot', type:'alloy'},
        {name: 'iron ingot', type:'alloy'},
        {name: 'silver ingot', type:'alloy'},
        {name: 'tin ingot', type:'alloy'},
        {name: 'alloy', type:'alloy'},
        {name: 'amethyst', type:'crystal'},
        {name: 'calcite', type:'crystal'},
        {name: 'herkimer', type:'crystal'},
        {name: 'pearl', type:'crystal'},
        {name: 'quartz', type:'crystal'},
        {name: 'tellurite', type:'crystal'},
        {name: 'crystal', type:'crystal'},
        {name: 'diamond', type:'gem'},
        {name: 'emerald', type:'gem'},
        {name: 'garnet', type:'gem'},
        {name: 'opal', type:'gem'},
        {name: 'ruby', type:'gem'},
        {name: 'sunstone', type:'gem'},
        {name: 'gem', type:'gem'},
        {name: 'flake salt', type:'salt'},
        {name: 'iodine', type:'salt'},
        {name: 'kala namak', type:'salt'},
        {name: 'pink salt', type:'salt'},
        {name: 'rock salt', type:'salt'},
        {name: 'sea salt', type:'salt'},
        {name: 'salt', type:'salt'},
        {name: 'fleece', type:'hide'},
        {name: 'fur', type:'hide'},
        {name: 'hair', type:'hide'},
        {name: 'leather', type:'hide'},
        {name: 'pelt', type:'hide'},
        {name: 'skin', type:'hide'},
        {name: 'hide', type:'hide'},
        {name: 'carapace', type:'keratanoid'},
        {name: 'karatanoid', type:'keratanoid'},
        {name: 'bone', type:'keratanoid'},
        {name: 'residue', type:'keratanoid'},
        {name: 'scale', type:'keratanoid'},
        {name: 'shell', type:'keratanoid'},
        {name: 'gneric karatanoid', type:'keratanoid'},
        {name: 'brain coral', type:'coral/paste'},
        {name: 'fire coral', type:'coral/paste'},
        {name: 'organic paste', type:'coral/paste'},
        {name: 'organic paste coral', type:'coral/paste'},
        {name: 'blubber', type:'oil'},
        {name: 'crude oil', type:'oil'},
        {name: 'fish oil', type:'oil'},
        {name: 'mineral oil', type:'oil'},
        {name: 'naptha', type:'oil'},
        {name: 'shale oil', type:'oil'},
        {name: 'oil', type:'oil'},
        {name: 'mythos', type:'mythos'}        
      ]);
    });
};
						