
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('resources').del()
    .then(function () {
      // Inserts seed entries
      return knex('resources').insert([
        {name: 'bamboo', gold_value: 0.01, type:'fibers'},
        {name: 'cotton', gold_value: 0.01, type:'fibers'},
        {name: 'hemp', gold_value: 0.01, type:'fibers'},
        {name: 'jute', gold_value: 0.01, type:'fibers'},
        {name: 'seaweed', gold_value: 0.01, type:'fibers'},
        {name: 'silk', gold_value: 0.01, type:'fibers'},
        {name: 'straw', gold_value: 0.01, type:'fibers'},
        {name: 'fibers', gold_value: 0.01, type:'fibers'},
        {name: 'bark', gold_value: 0.01, type:'thatch'},
        {name: 'fronds', gold_value: 0.01, type:'thatch'},
        {name: 'reeds', gold_value: 0.01, type:'thatch'},
        {name: 'roots', gold_value: 0.01, type:'thatch'},
        {name: 'rushes', gold_value: 0.01, type:'thatch'},
        {name: 'twigs', gold_value: 0.07, type:'thatch'},
        {name: 'thatch', gold_value: 0.01, type:'thatch'},
        {name: 'agedwood', gold_value: 0.03, type:'wood'},
        {name: 'darkwood', gold_value: 0.05, type:'wood'},
        {name: 'lightwood', gold_value: 0.03, type:'wood'},
        {name: 'softwood', gold_value: 0.03, type:'wood'},
        {name: 'strongwood', gold_value: 0.03, type:'wood'},
        {name: 'wetwood', gold_value: 0.03, type:'wood'},
        {name: 'ironwood', gold_value: 0.05, type:'wood'},
        {name: 'wood', gold_value: 0.03, type:'wood'},
        {name: 'honey', gold_value: 0.03, type:'sugar'},
        {name: 'gum', gold_value: 0.03, type:'sugar'},
        {name: 'nectar', gold_value: 0.03, type:'sugar'},
        {name: 'sugars', gold_value: 0.03, type:'sugar'},
        {name: 'sugarcane', gold_value: 0.03, type:'sugar'},
        {name: 'syrup', gold_value: 0.03, type:'sugar'},
        {name: 'resin', gold_value: 0.03, type:'sugar'},
        {name: 'sugars', gold_value: 0.03, type:'sugar'},
        {name: 'anthracite', gold_value: 0.01, type:'coal'},
        {name: 'graphite', gold_value: 0.01, type:'coal'},
        {name: 'lignite', gold_value: 0.01, type:'coal'},
        {name: 'nitre', gold_value: 0.01, type:'coal'},
        {name: 'peat', gold_value: 0.01, type:'coal'},
        {name: 'sulfer', gold_value: 0.01, type:'coal'},
        {name: 'coal', gold_value: 0.01, type:'coal'},
        {name: 'agate', gold_value: 2.0, type:'flint'},
        {name: 'basalt', gold_value: 0.01, type:'flint'},
        {name: 'chalcedony', gold_value: 0.01, type:'flint'},
        {name: 'chert', gold_value: 0.01, type:'flint'},
        {name: 'obsidian', gold_value: 0.2, type:'flint'},
        {name: 'radiolarite', gold_value: 0.01, type:'flint'},
        {name: 'flint', gold_value: 0.01, type:'flint'},
        {name: 'coquina', gold_value: 0.03, type:'stone'},
        {name: 'granite', gold_value: 0.03, type:'stone'},
        {name: 'limestone', gold_value: 0.03, type:'stone'},
        {name: 'marble', gold_value: 0.03, type:'stone'},
        {name: 'sandstone', gold_value: 0.03, type:'stone'},
        {name: 'slate', gold_value: 0.03, type:'stone'},
        {name: 'stone', gold_value: 0.03, type:'stone'},
        {name: 'cobalt', gold_value: 0.07, type:'metal'},
        {name: 'copper', gold_value: 0.07, type:'metal'},
        {name: 'iridium', gold_value: 0.1, type:'metal'},
        {name: 'iron', gold_value: 0.07, type:'metal'},
        {name: 'silver', gold_value: 0.07, type:'metal'},
        {name: 'tin', gold_value: 0.07, type:'metal'},
        {name: 'metal', gold_value: 0.07, type:'metal'},
        {name: 'cobalt ingot', gold_value: 0.16, type:'alloy'},
        {name: 'copper ingot', gold_value: 0.16, type:'alloy'},
        {name: 'iridium ingot', gold_value: 0.16, type:'alloy'},
        {name: 'iron ingot', gold_value: 0.16, type:'alloy'},
        {name: 'silver ingot', gold_value: 0.16, type:'alloy'},
        {name: 'tin ingot', gold_value: 0.16, type:'alloy'},
        {name: 'alloy', gold_value: 0.16, type:'alloy'},
        {name: 'amethyst', gold_value: 0.05, type:'crystal'},
        {name: 'calcite', gold_value: 0.05, type:'crystal'},
        {name: 'herkimer', gold_value: 0.05, type:'crystal'},
        {name: 'pearl', gold_value: 0.05, type:'crystal'},
        {name: 'quartz', gold_value: 0.05, type:'crystal'},
        {name: 'tellurite', gold_value: 0.05, type:'crystal'},
        {name: 'crystal', gold_value: 0.05, type:'crystal'},
        {name: 'diamond', gold_value: 0.05, type:'gem'},
        {name: 'emerald', gold_value: 0.05, type:'gem'},
        {name: 'garnet', gold_value: 0.05, type:'gem'},
        {name: 'opal', gold_value: 0.05, type:'gem'},
        {name: 'ruby', gold_value: 0.05, type:'gem'},
        {name: 'sunstone', gold_value: 0.05, type:'gem'},
        {name: 'gem', gold_value: 0.05, type:'gem'},
        {name: 'flake salt', gold_value: 0.02, type:'salt'},
        {name: 'iodine', gold_value: 0.02, type:'salt'},
        {name: 'kala namak', gold_value: 0.02, type:'salt'},
        {name: 'pink salt', gold_value: 0.02, type:'salt'},
        {name: 'rock salt', gold_value: 0.02, type:'salt'},
        {name: 'sea salt', gold_value: 0.02, type:'salt'},
        {name: 'salt', gold_value: 0.02, type:'salt'},
        {name: 'fleece', gold_value: 0.02, type:'hide'},
        {name: 'fur', gold_value: 0.02, type:'hide'},
        {name: 'hair', gold_value: 0.02, type:'hide'},
        {name: 'leather', gold_value: 0.02, type:'hide'},
        {name: 'pelt', gold_value: 0.02, type:'hide'},
        {name: 'skin', gold_value: 0.02, type:'hide'},
        {name: 'hide', gold_value: 0.02, type:'hide'},
        {name: 'carapace', gold_value: 0.1, type:'keratanoid'},
        {name: 'karatanoid', gold_value: 0.02, type:'keratanoid'},
        {name: 'bone', gold_value: 0.02, type:'keratanoid'},
        {name: 'residue', gold_value: 0.2, type:'keratanoid'},
        {name: 'scale', gold_value: 0.02, type:'keratanoid'},
        {name: 'shell', gold_value: 0.02, type:'keratanoid'},
        {name: 'gneric karatanoid', gold_value: 0.02, type:'keratanoid'},
        {name: 'brain coral', gold_value: 0.01, type:'coral'},
        {name: 'fire coral', gold_value: 0.01, type:'coral'},
        {name: 'organic paste', gold_value: 0.04, type:'paste'},
        {name: 'organic paste coral', gold_value: 0.04, type:'paste'},
        {name: 'blubber', gold_value: 0.07, type:'oil'},
        {name: 'crude oil', gold_value: 0.05, type:'oil'},
        {name: 'fish oil', gold_value: 0.05, type:'oil'},
        {name: 'mineral oil', gold_value: 0.05, type:'oil'},
        {name: 'naptha', gold_value: 0.05, type:'oil'},
        {name: 'shale oil', gold_value: 0.05, type:'oil'},
        {name: 'oil', gold_value: 0.05, type:'oil'},
        {name: 'mythos', gold_value: 2.0, type:'mythos'},
        {name: 'gunpowder', gold_value: 0.03, type:'craftables'},
        {name: 'blasting powder', gold_value: 0.17, type:'craftables'},
        {name: 'fire gel', gold_value: 0.07, type:'craftables'},
        {name: 'perserving salt', gold_value: 0.03, type:'craftables'},       
      ]);
    });
};
						